package imat;
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;


public class kundvagnsCard extends javax.swing.JPanel {
    
    // My variables
    private List<Recipe> recipeList;
    
    /** Creates new form RecipeListCard */
    public kundvagnsCard(List<Recipe> recipeList) {
        // Swing initialization
        initComponents();
        // My initialization
        this.recipeList = recipeList;
        initList();
        addListener();
    }
    
    private void initList() {
        recipeJList.setFixedCellHeight(90);
        RecipeCell[] recipes = new RecipeCell[recipeList.size()];
        
        JButton delete = new JButton();
        // Fill the array recipes with RecipeCells
        for (int i = 0; i < recipes.length; i++) {
            Recipe recipe = recipeList.get(i);
            recipes[i] = new RecipeCell(recipe.getName(),,
                    recipe.getPrice(), recipe.getImage())+ delete;
            
            
            
            /*************** TODO *************************
             * LÄGG IN TA BORT KNAPP
             * TEXTFÄLT FÖR ANTAL
             */
        }
        // Add recipes to the JList
        recipeJList.setListData(recipes);
        recipeJList.setCellRenderer(new RecipeCellRenderer());
    }
    
    private void addListener() {
        recipeJList.addMouseListener( new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                int index = recipeJList.getSelectedIndex();
                Recipe recipe = recipeList.get(index);
                // Change card to RecipeCard
                MainCard mainCard = (MainCard)getParent();
                mainCard.setRecipeCard(recipe, recipeList);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recipeJList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        saveCartBtn = new javax.swing.JButton();
        emptyBtn = new javax.swing.JButton();
        payBtn = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        recipeJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        recipeJList.setName("recipeJList"); // NOI18N
        jScrollPane1.setViewportView(recipeJList);

        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(kundvagnsCard.class);
        saveCartBtn.setText(resourceMap.getString("saveCartBtn.text")); // NOI18N
        saveCartBtn.setName("saveCartBtn"); // NOI18N

        emptyBtn.setText(resourceMap.getString("emptyBtn.text")); // NOI18N
        emptyBtn.setName("emptyBtn"); // NOI18N

        payBtn.setText(resourceMap.getString("payBtn.text")); // NOI18N
        payBtn.setName("payBtn"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(saveCartBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emptyBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(payBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saveCartBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(emptyBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(payBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(104, 104, 104)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 390, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 36, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton emptyBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payBtn;
    private javax.swing.JList recipeJList;
    private javax.swing.JButton saveCartBtn;
    // End of variables declaration//GEN-END:variables
}
