package imat;

import java.util.*;
import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import se.chalmers.ait.dat215.project.*;

public class kvittoCard extends javax.swing.JPanel {
    
    // My variables
    private List<Product> kvittoList;
    
    /** Creates new form RecipeListCard */
    public kvittoCard(List<Product> kvittoList) {
        // Swing initialization
        initComponents();
        // My initialization
        this.kvittoList = kvittoList;
        initList();
        addListener();
    }
    
    private void initList() {
        recipeJList.setFixedCellHeight(90);
        RecipeCell[] recipes = new RecipeCell[kvittoList.size()];
        // Fill the array recipes with RecipeCells
        for (int i = 0; i < recipes.length; i++) {
            Product product = kvittoList.get(i);
            //recipes[i] = new RecipeCell(product.getName(),
              //      product.getPrice());
            
            
            
            
            
            
        }
        // Add recipes to the JList
        recipeJList.setListData(recipes);
        recipeJList.setCellRenderer(new RecipeCellRenderer());
    }
    
    private void addListener() {
        recipeJList.addMouseListener( new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                int index = recipeJList.getSelectedIndex();
                Recipe recipe = recipeList.get(index);
                // Change card to RecipeCard
                MainCard mainCard = (MainCard)getParent();
                mainCard.setRecipeCard(recipe, recipeList);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recipeJList = new javax.swing.JList();
        topBar1 = new imat.topBar();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        adressLabel = new javax.swing.JLabel();
        postNrLabel = new javax.swing.JLabel();
        orderInfoLabel = new javax.swing.JLabel();
        orderRecievedLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mailBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        recipeJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        recipeJList.setName("recipeJList"); // NOI18N
        jScrollPane1.setViewportView(recipeJList);

        topBar1.setName("topBar1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(kvittoCard.class);
        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        adressLabel.setText(resourceMap.getString("adressLabel.text")); // NOI18N
        adressLabel.setName("adressLabel"); // NOI18N

        postNrLabel.setText(resourceMap.getString("postNrLabel.text")); // NOI18N
        postNrLabel.setName("postNrLabel"); // NOI18N

        orderInfoLabel.setText(resourceMap.getString("orderInfoLabel.text")); // NOI18N
        orderInfoLabel.setName("orderInfoLabel"); // NOI18N

        orderRecievedLabel.setText(resourceMap.getString("orderRecievedLabel.text")); // NOI18N
        orderRecievedLabel.setName("orderRecievedLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameLabel)
                    .add(adressLabel)
                    .add(postNrLabel)
                    .add(orderInfoLabel)
                    .add(orderRecievedLabel))
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(nameLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(adressLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(postNrLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(orderInfoLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(orderRecievedLabel)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setName("jPanel2"); // NOI18N

        mailBtn.setText(resourceMap.getString("mailBtn.text")); // NOI18N
        mailBtn.setName("mailBtn"); // NOI18N
        mailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailBtnActionPerformed(evt);
            }
        });

        homeBtn.setText(resourceMap.getString("homeBtn.text")); // NOI18N
        homeBtn.setName("homeBtn"); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(mailBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(homeBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(mailBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(homeBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
            .add(topBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(topBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(38, 38, 38)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void mailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailBtnActionPerformed
JOptionPane.showMessageDialog(this,"Kvittot har mailats!");
}//GEN-LAST:event_mailBtnActionPerformed

private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
    MainCard mainCard = (MainCard)getParent();
    mainCard.setRecipeListCard(recipeList);
}//GEN-LAST:event_homeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressLabel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mailBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel orderInfoLabel;
    private javax.swing.JLabel orderRecievedLabel;
    private javax.swing.JLabel postNrLabel;
    private javax.swing.JList recipeJList;
    private imat.topBar topBar1;
    // End of variables declaration//GEN-END:variables
}
