package imat;

import java.util.List;
import javax.swing.ImageIcon;
import se.chalmers.ait.dat215.lab2.Recipe;

public class RecipeCard extends javax.swing.JPanel {

    // My variables
    private Recipe recipe;
    private List<Recipe> recipeList; // Storing last recipe for going back
    
    /** Creates new form RecipeCard */
    public RecipeCard(Recipe recipe, List<Recipe> recipeList) {
        // Swing initialization
        initComponents();
        // My initialization
        this.recipe = recipe;
        this.recipeList = recipeList;
        showRecipeInfo();
    }

    private void showRecipeInfo() {
        nameLabel.setText(recipe.getName());
        ImageIcon imgIcon = new ImageIcon(this.getClass().getResource("resources/recipe1.jpg"));
        imgLabel.setIcon(imgIcon);
        cuisineLabel.setText("Kök: " + recipe.getCuisine());
        mainIngredientLabel.setText("Huvudingrediens: " + recipe.getMainIngredient());
        servingsLabel.setText("Portioner: " + recipe.getServings() + "st");
        priceLabel.setText("Pris: " + recipe.getPrice() + "kr");
        timeLabel.setText("Tid: " + recipe.getPrice() + "min");
        difficultyLabel.setText("Svårighetsgrad: " + recipe.getDifficulty());
        matchLabel.setText("Matchar sökningen: " + recipe.getMatch() + "%");
        
        ingredientsLabel.setText(ingredientsLabelString());
        descriptionLabel.setText(descriptionLabelString());
    }
    
    private String ingredientsLabelString() {
        String returnString = "<html><b>Ingredienser:</b><br>";
        for (int i = 0; i < recipe.getIngredients().size(); i++) {
            returnString += recipe.getIngredients().get(i).toString();
            returnString += "<br>";
        }
        returnString += "</html>";
        return returnString;
    }
    
    private String descriptionLabelString() {
        String returnString = "<html><b>Gör så här:</b><br>";
        returnString += recipe.getDescription();
        returnString += "</html>";
        return returnString;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ingredientsLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imagePanel = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        cuisineLabel = new javax.swing.JLabel();
        mainIngredientLabel = new javax.swing.JLabel();
        servingsLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        matchLabel = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lab2.Lab2App.class).getContext().getResourceMap(RecipeCard.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        backBtn.setText(resourceMap.getString("backBtn.text")); // NOI18N
        backBtn.setToolTipText(resourceMap.getString("backBtn.toolTipText")); // NOI18N
        backBtn.setName("backBtn"); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        nameLabel.setFont(resourceMap.getFont("nameLabel.font")); // NOI18N
        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        ingredientsLabel.setText(resourceMap.getString("ingredientsLabel.text")); // NOI18N
        ingredientsLabel.setName("ingredientsLabel"); // NOI18N

        descriptionLabel.setText(resourceMap.getString("descriptionLabel.text")); // NOI18N
        descriptionLabel.setName("descriptionLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ingredientsLabel)
                    .add(descriptionLabel))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(ingredientsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(descriptionLabel)
                .addContainerGap(408, Short.MAX_VALUE))
        );

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        imagePanel.setName("imagePanel"); // NOI18N

        imgLabel.setText(resourceMap.getString("imgLabel.text")); // NOI18N
        imgLabel.setName("imgLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout imagePanelLayout = new org.jdesktop.layout.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanelLayout.createSequentialGroup()
                .add(imgLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imgLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );

        cuisineLabel.setText(resourceMap.getString("cuisineLabel.text")); // NOI18N
        cuisineLabel.setName("cuisineLabel"); // NOI18N

        mainIngredientLabel.setText(resourceMap.getString("mainIngredientLabel.text")); // NOI18N
        mainIngredientLabel.setName("mainIngredientLabel"); // NOI18N

        servingsLabel.setText(resourceMap.getString("servingsLabel.text")); // NOI18N
        servingsLabel.setName("servingsLabel"); // NOI18N

        priceLabel.setText(resourceMap.getString("priceLabel.text")); // NOI18N
        priceLabel.setName("priceLabel"); // NOI18N

        timeLabel.setText(resourceMap.getString("timeLabel.text")); // NOI18N
        timeLabel.setName("timeLabel"); // NOI18N

        difficultyLabel.setText(resourceMap.getString("difficultyLabel.text")); // NOI18N
        difficultyLabel.setName("difficultyLabel"); // NOI18N

        matchLabel.setText(resourceMap.getString("matchLabel.text")); // NOI18N
        matchLabel.setName("matchLabel"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanel2Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(matchLabel)
                    .add(difficultyLabel)
                    .add(timeLabel)
                    .add(priceLabel)
                    .add(servingsLabel)
                    .add(mainIngredientLabel)
                    .add(cuisineLabel))
                .add(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cuisineLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainIngredientLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(servingsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(priceLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(timeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(difficultyLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 106, Short.MAX_VALUE)
                .add(matchLabel)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(backBtn)
                        .add(92, 92, 92)
                        .add(nameLabel))
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(backBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameLabel))
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    MainCard mainCard = (MainCard)getParent();
    mainCard.setRecipeListCard(recipeList);
}//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cuisineLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel ingredientsLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel servingsLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
